spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/healthcare
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

  jpa:
    hibernate:
      ddl-auto: update   # auto-create/update tables based on entities
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always       # run schema/data.sql if present

logging:
  level:
    root: INFO                # show INFO, WARN, ERROR globally
    org.springframework: ERROR  # only show errors from Spring
    org.springframework.http.converter: ERROR
    org.hibernate: ERROR       # only show errors from Hibernate
    com.healthcare: DEBUG      # show DEBUG, INFO, WARN, ERROR from your app

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
