/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.healthcare;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class HealthcareBackendApplication {

    public static void main(String[] args) {
        SpringApplication.run(HealthcareBackendApplication.class, args);
    }
    public Object getGreeting() {
        System.out.println("Hello World!");
        return "app should have a greeting";
    }
}



