/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.healthcare;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class HealthcareBackendApplicationTest {
    @Test void appHasAGreeting() {
        HealthcareBackendApplication classUnderTest = new HealthcareBackendApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
